### ISSUE TITLE
Bug?  Building does not show up after import OSM data.

### ISSUE THREAD

**Issue by kelfire** [ue4plugins/StreetMap#1]
Buildings are not showing up for me.  Anyone having the same issue?  I imported the OSM data then set it in the Streetmap component.

![streetmap](https://cloud.githubusercontent.com/assets/13243988/21583441/b12f5798-d035-11e6-9281-eb85259a9f92.png)

**Comment by kelfire** [comment]
never mind looks like some location doesn't have building data?

**Comment by RaceTheMaSe** [comment]
either that or buildings don't have height information. Look at StreetMapComponent.cpp GenerateMesh() to see what happens with those buildings. You can add a default height for building here or in the OSM parsing stage.

**Comment by MikeFricker** [comment]
Yeah, a lot of smaller cities are missing height values for buildings.  Also, we're currently ignoring height values if they are stored in the XML file with "units" attached to it.  We don't parse the units field, so the height value gets skipped.  I think this is pretty uncommon though.
