### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by markspolakovs** [ue4plugins/StreetMap#12]
See [answerhub question](https://answers.unrealengine.com/questions/565238/errors-compiling-osm-plugin.html). When trying to add the project, I get [errors](http://pastebin.com/74HQ1wfH) of the kind `'LastDetailBuilderPtr': undeclared identifier` or `left of '.Num' must have class/struct/union`. I'm using UE4.15 with Visual Studio 2015.

**Comment by mcpirate** [comment]
++

**Comment by MikeFricker** [comment]
The plugin hasn't been updated for 4.15 yet.  4.15 introduced some changes to how engine and editor header files should be included.  I'll try to get it updated later today.  Meanwhile you can use 4.14 if you'd like.

**Comment by MikeFricker** [comment]
Should be working now!  Give it a try. :)
