### ISSUE TITLE
how to insert the plugin currectly?

### ISSUE THREAD

**Issue by Enrys** [ue4plugins/StreetMap#15]
i try to do anything... but when i start the project says this: https://drive.google.com/open?id=0B1p70WArgsPbV3l0YWdLUTRKNGM

**Comment by Hemofektik** [comment]
Did you compile UE4 from source code?

**Comment by V4nish** [comment]
Is there any other way to run the plugin without error( https://drive.google.com/open?id=0B1p70WArgsPbV3l0YWdLUTRKNGM), or I just can't avoid visual studio?

**Comment by Hemofektik** [comment]
Currently, you cannot run it without the UE4 source code and a compiler installed on your machine.

**Comment by V4nish** [comment]
Thank you for response. My last question, is it possible, that in future the plugin will run without compiling project with VS?

**Comment by Hemofektik** [comment]
In theory yes. Someone would have to create releases including the binaries.

**Comment by MikeFricker** [comment]
There is currently no plan to precompile binaries for the plugin, but I'll keep it in mind for later.
