### ISSUE TITLE
OSM not listed as a supported file type

### ISSUE THREAD

**Issue by noorbeast** [ue4plugins/StreetMap#20]
I compiled the VR 4.16 branch of Unreal from source, created the Plugins folder and copied StreetMap there then built the project. 

Unfortunately it won't let me import an osm file and osm is not listed as a file type option in the Import selection File window.

**Comment by Hemofektik** [comment]
Did you check if the Plugin is actually loaded? Open the Plugins Window in the Editor and view Importers Category to verify.

**Comment by RaceTheMaSe** [comment]
From what I've read it should even fail to compile. There was a change in the build.cs file for 4.16 that hasn't been added to StreetMap yet. Example:
```
4.15:
- public PluginName(TargetInfo Target) { ...

4.16:
- public PluginName(ReadOnlyTargetRules Target) : base(Target) { ...
```

**Comment by noorbeast** [comment]
Checked and it is not loaded.

**Comment by Hemofektik** [comment]
So it did work after enabling it?

**Comment by noorbeast** [comment]
Unfortunately it did not show as an option to be enabled.

But nor were there compile errors.

**Comment by jegumhon** [comment]
Did anybody solve this problem?
I got same case

**Comment by MikeFricker** [comment]
The plugin is confirmed to work in 4.17 after the latest commits.  Make sure to rebuild the plugin by cloning it to your project's plugins folder and recompiling your project, then enabling it in the Plugins UI of the editor and restarting.
