### ISSUE TITLE
compile StreetMap in Linux

### ISSUE THREAD

**Issue by miluit01** [ue4plugins/StreetMap#21]
Hello Mike,

I am trying to compile StreetMap in Linux.
I have copied the StreeMap folder in UnrealEngine/Engine/Plugins
After that I have run ./GenerateProjectFiles.sh then make
But i got following errors:

`.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapRuntime/PolygonTools.cpp(1): error: Expected PolygonTools.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapRuntime/StreetMap.cpp(1): error: Expected StreetMap.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapRuntime/StreetMapActor.cpp(1): error: Expected StreetMapActor.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapRuntime/StreetMapComponent.cpp(1): error: Expected StreetMapComponent.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapRuntime/StreetMapSceneProxy.cpp(1): error: Expected StreetMapSceneProxy.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/OSMFile.cpp(1): error: Expected OSMFile.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapActorFactory.cpp(1): error: Expected StreetMapActorFactory.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapAssetTypeActions.cpp(1): error: Expected StreetMapAssetTypeActions.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapComponentDetails.cpp(1): error: Expected StreetMapComponentDetails.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapFactory.cpp(1): error: Expected StreetMapFactory.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapReimportFactory.cpp(1): error: Expected StreetMapReimportFactory.h to be first header included.
.../UnrealEngine/Engine/Plugins/StreetMap/Source/StreetMapImporting/StreetMapStyle.cpp(1): error: Expected StreetMapStyle.h to be first header included.
Build canceled.`

I am using the current master branch (e55015396bca11b84e4e846c5500955880294d76). Can you please tell me which Unreal release works with StreetMap plugin?

**Comment by MikeFricker** [comment]
Thanks, will look into Linux compilation when I can.  You should be able to use the latest release (4.17) after today's commits.
