### ISSUE TITLE
StreetMap plugin is not compatible with the current engine version

### ISSUE THREAD

**Issue by kadartamascsaba** [ue4plugins/StreetMap#22]
Hi,

I tried to install Streetmap plugin, but I got a warning message.

![screenshot00](https://user-images.githubusercontent.com/15170619/29994725-26b11f46-8f8b-11e7-9d3e-2caabe1e1ddb.PNG)

Could you help me to modify it so I can use it on 4.17.1 Unreal Engine?

Thanks in advance!

**Comment by Hemofektik** [comment]
Hi, this project does not seem to be actively maintained here anymore. But there is a 4.17 compatible version available: https://github.com/Real-Synth/StreetMap/tree/Railroad

**Comment by Alchemy-Meister** [comment]
Regarding @Hemofektik Railroad fork I have been trying to build a project on latest branch on version 4.17.1 that contains this plugin without success.

The steps executed are the following:
1. Create and empty c++ class actor.
2. Generate Visual Studio project files.
3. Build the project from VS.
4. Check the tick on Settings>Plugins and restart the editor.
5. Rebuild UE4Editor - StreetMapImporting.dll and StreetMapRuntime.dll, as it reports that they are built for another engine version.

However the StreetMapImporting fails to build the StreetMapImporting.dll with the following errors:
`Module.StreetMapImporting.cpp
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(39): error C2248: 'ULandscapeSplinesComponent::ControlPoints': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(128): note: see declaration of 'ULandscapeSplinesComponent::ControlPoints'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(89): error C2248: 'ULandscapeSplinesComponent::Segments': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(131): note: see declaration of 'ULandscapeSplinesComponent::Segments'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(215): error C2248: 'ULandscapeSplinesComponent::Segments': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(131): note: see declaration of 'ULandscapeSplinesComponent::Segments'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(218): error C2248: 'ULandscapeSplinesComponent::Segments': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(131): note: see declaration of 'ULandscapeSplinesComponent::Segments'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(227): error C2248: 'ULandscapeSplinesComponent::Segments': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(131): note: see declaration of 'ULandscapeSplinesComponent::Segments'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
E:\Projects\Maps\Plugins\StreetMap\Source\StreetMapImporting\StreetMapSplineTools.cpp(231): error C2248: 'ULandscapeSplinesComponent::ControlPoints': cannot access protected member declared in class 'ULandscapeSplinesComponent'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplinesComponent.h(128): note: see declaration of 'ULandscapeSplinesComponent::ControlPoints'
E:\Engines\UE_4.17\Engine\Source\Runtime\Landscape\Classes\LandscapeSplineControlPoint.h(16): note: see declaration of 'ULandscapeSplinesComponent'
ERROR: UBT ERROR: Failed to produce item: E:\Projects\Maps\Plugins\StreetMap\Binaries\Win64\UE4Editor-StreetMapImporting.dll
Total build time: 16.00 seconds (Local executor: 0.00 seconds)
LogInit: Warning: Still incompatible or missing module: UE4Editor-StreetMapImporting.dll`

Is there something that I'm missing?

Best regards.

**Comment by Hemofektik** [comment]
Argh sorry. I forgot, that this is also not compatible with UE4 default because they do not allow ULandscapeSplinesComponents to be modified from code. You could fix it by adding  "friend class FStreetMapSplineTools" to the ULandscapeSplinesComponent class at the bottom of its header where already some friend classes are defined. Or you comment out the code in StreetMapSplineTools.cpp which would remove some of the new functionality I added.
Sorry.

**Comment by Alchemy-Meister** [comment]
By adding the friend class to ULandscapeSplinesComponent it was able to build the dll and access to the project with the plugin enabled. The plugin seems to be working properly as it recognizes .osm as an importing extension. However it sometimes fails to import osm file. I am trying to figure it out if has to do with "'" string or maybe non ascii characters being inside of value. However the UE Editor Output Log is not very helpful to trace the error.

Anyways, thanks for contribution and support, you solved my main problem.

**Comment by Hemofektik** [comment]
A new feature was added in the last weeks to be able to parse 'strings' instead of only "strings" for xml files as you already suspected. This is an issue of 4.17.1+. I had no time to file a bug for it yet.

**Comment by kadartamascsaba** [comment]
Thank you very much!

**Comment by SRBenham** [comment]
Hey can yo believe that some one is still trying to use the Street maps plugin.... Yes it's me. lol

anyways i am using it in 4.17 and up till the point I need to import the "osm" it is fine. than it gives me a line error the line for the error is 8461.
which is a tag for a street name. I am new to the game programming and I would like to see if I can get this to work, as I think its a fantastic Idea for a plugin

[Medicine_Hat_Downtown.zip](https://github.com/ue4plugins/StreetMap/files/2065559/Medicine_Hat_Downtown.zip)

**Comment by RaceTheMaSe** [comment]
About the XML parser I did some work on this. Still not merged in the official code, but here is the Pull request:
https://github.com/EpicGames/UnrealEngine/pull/4132

**Comment by SRBenham** [comment]
Thanks, appreciate the input, but I found a workaround. used 4.16 saved the mesh than manually took it and put it in a 4,19 and it worked.

Cool piece of work, I really like it as the city I am in is full of coolies, If I could do a topography I would be set.

Just one last question can the plugin do topography?

Bill

**Comment by varshakdas** [comment]
I tried it with 4.14 by making some changes in build.cs it worked fine for
me thank you fr ur support

**Comment by SRBenham** [comment]
cool, thanks

On Mon, Jun 4, 2018 at 3:00 AM, Max Seidenstuecker <notifications@github.com
