### ISSUE TITLE
import doesn't work

### ISSUE THREAD

**Issue by ojw0618** [ue4plugins/StreetMap#24]
I just downloaded the file and followed the instruction here but when I pressed import button, it gives me errors and doesn't run appropriately.
![22092861_10155494303820590_1787016122_o](https://user-images.githubusercontent.com/10768526/30913073-20fbfc5e-a34c-11e7-917e-dd021ff7761f.png)

**Comment by Hemofektik** [comment]
You probably mixed up the Repositories. This one is the OSM Plugin for the Unreal Engine 4.
You where probably looking to create an issue there: https://github.com/vvoovv/blender-osm
