### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by Blastyu** [ue4plugins/StreetMap#25]
Hello in first , im French sorry, for my bad english :) thanks you .
today i try this plugins in unreal engine version 4.17.2 i install them in a c++ project . 
but when i want to import a map.osm i have a message like that :
![capture 1](https://user-images.githubusercontent.com/32417722/31047351-405f8678-a609-11e7-97f6-d70a769c5660.JPG)

and when i go in the output logs i seee that : 
![capture 2](https://user-images.githubusercontent.com/32417722/31047359-5baa3fea-a609-11e7-8839-9e3c7e1083d7.JPG)

i don't konw how to resolve that and i search everywhere but  i find nothing . 
thanks you for your help and i hope this problem can be resolve :) thanks you ^^

**Comment by Hemofektik** [comment]
In your OSM file, there is most probably a tag some lines above the mentioned line in the log which uses mixed apostrophes (e.g. "The Restaraunt 'A Lion'"). A bug in the XML parsing of the UE4 causes this issue. remove the inner apostrophes in the OSM file and it will import happily.

**Comment by Blastyu** [comment]
thanks you a lot :) i try that and isay you if it works thanks you :)

**Comment by Blastyu** [comment]
thanks you a lot it work you are the best :) thanks you and good day ^^

**Comment by RaceTheMaSe** [comment]
Thanks Richard, ran into the same problem with Nuerburgring area yesterday. That fixes the problem! :-)

**Comment by varshakdas** [comment]
Could you please tell me the changes to make while importing the module to the version 4.14

**Comment by varshakdas** [comment]
Itried with 4.14 it worked now perfectly.  Thank you for your support
