### ISSUE TITLE
Packaging for Android not possible

### ISSUE THREAD

**Issue by Torloy** [ue4plugins/StreetMap#26]
Whenever I try to package a project for Android while the plugin is installed, it aborts the process.
Removing the plugin again solves the problem, but it's not helping much.
Sorry for the German parts in the Log.

Here are the Errors I recieve:
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: ERROR: Unable to instantiate instance of 'HLSLCC' object type from compiled assembly 'UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.  Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requiremen
ts.  The CLR exception details may provide more information:  System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> UnrealBuildTool.BuildException: ERROR: Attempt to build against HLSLCC on unsupported platform Android

UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Software\Engine\Unreal\UE_4.17\Engine\Binaries\DotNET\UnrealBuildTool.exe DungeonGoPlug Android Development -Project=C:\Users\diadi\Documents\SAE\
GPR916\Diploma\DungeonGoPlug\DungeonGoPlug.uproject  C:\Users\diadi\Documents\SAE\GPR916\Diploma\DungeonGoPlug\DungeonGoPlug.uproject -NoUBTMakefiles  -remoteini="C:\Users\diadi\Documents\SAE\GPR916\Diploma\DungeonGoPlug" -skipdeploy -noxge -generatemanifest -NoHotReload. See logfile for details: 'UnrealBuildTool-2017.10.11-02.21.50.txt'

PackagingResults: Error: Unknown Error

The full Output Log is attached.
[Package.txt](https://github.com/ue4plugins/StreetMap/files/1373807/Package.txt)

**Comment by dineshone** [comment]
Hi,

Can you try unchecking the option 'ASTC'  texture from the Texture formats. Also, I don't usually use openGL 3.0. Can you change the open gl version to 2.0 and see if the problem exists?

Thanks
Dinesh

**Comment by Torloy** [comment]
Hello,

so I tried Open GL 2 and also Vulkan. And I tried to package the game with each Texture format alone. Every single time it would abort the process.

Greetings,
Torloy

**Comment by natakaro** [comment]
Remove "PropertyEditor" in StreetMapRuntime.Build.cs :)

**Comment by vinfamy** [comment]
I can confirm this problem occurs when trying to package for Windows 64 bit too. Natakaro's solution of removing"PropertyEditor" in StreetMapRuntime.Build.cs solves it.
