### ISSUE TITLE
Not working with UE 4.17.2

### ISSUE THREAD

**Issue by ArtyomIsFlash** [ue4plugins/StreetMap#27]
![default](https://user-images.githubusercontent.com/8017858/31577576-d93e64ca-b119-11e7-89eb-65184389132f.png)
This is the message that pops out when I run my project.

**Comment by ArtyomIsFlash** [comment]
Whoops, my bad. Didn't RTFM.

**Comment by rz300** [comment]
> Whoops, my bad. Didn't RTFM.

hey man, how did you start this plugin?
