### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by gooner442** [ue4plugins/StreetMap#28]
Hi,
![error](https://user-images.githubusercontent.com/33064601/31951618-8b98cbd8-b8d6-11e7-91b7-9b8d88c36ce8.PNG)
can you tell me have I placed the streetmap folder in the correct place?... I'm getting an error message when opening UE4 as seen in the image attached.
Thanks,
Martin

**Comment by Hemofektik** [comment]
The Plugin was not built. This Plugin currently only works with C++ Projects that automatically ask to build the plugins.
