### ISSUE TITLE
Newcomer of osm&ue4, need some help

### ISSUE THREAD

**Issue by 5guo** [ue4plugins/StreetMap#30]
hi, MikeFricker:
Here, I'm learning your plugins this week. Some problems trouble me for a long time, so your help and answers could be very important. 
1. I cannot found CMAKE file or Makefile in this repository, so how can I complete the task as "Rebuild your C++ project. The new plugin will be compiled too!"?
2. Do I need install ue4 before learning your project? And Macbook could be supportable for it, or only Windows?
3. My system is OS X, can you give some suggest soft or application to me?

**Comment by Hemofektik** [comment]
As stated in the documentation of this Plugin:

> This plug-in requires Visual Studio and either a C++ code project or the full Unreal Engine 4 source code from GitHub. If you are new to programming in UE4, please see the official Programming Guide!

This also works on OSX.

**Comment by 5guo** [comment]
Thank you, sooooo nice of you, I will try it this weekend.

**Comment by 5guo** [comment]
Hi, Mike, need your help again. I have 2 questions in my project.
1. I cannot build success after create a new C++ project(not blueprint project)?
2. Where should I execute the command "Rebuild" in your quick start description, UE4Editor or Xcode?

**Comment by MikeFricker** [comment]
Hey @5guo I'm closing this one out.  If you are still having problems let me know and we'll get you some help.
