### ISSUE TITLE
Build plugin on UE 4.17, Ubuntu 16.04?

### ISSUE THREAD

**Issue by n1ckfg** [ue4plugins/StreetMap#31]
Any advice on a Linux build of the plugin--has anyone else succeeded?

**Comment by Hemofektik** [comment]
You are right there is a parentheses issue in PolygonTools.h. But as soon as you fix it, it compiles fine.

**Comment by n1ckfg** [comment]
Hmm...I don't see any parentheses mistakes in PolygonTools.h--have you got a line number?

**Comment by Hemofektik** [comment]
It's in line 68. The compiler warns about probably missing parentheses and since warnings are marked as errors, it does not compile.
What are the problems you are facing to build the plugin?

**Comment by n1ckfg** [comment]
Yup, that fixed it--thanks! How did you find the location of the error; is it logged somewhere? (I didn't see any reference to the header file and line number in the error messages from the Editor I was getting before.)

**Comment by Hemofektik** [comment]
You have to compile your project from the terminal manually.

`make YourProjectNameEditor`

**Comment by n1ckfg** [comment]
Aha, thanks! First time building UE plugins on Linux for me.
