### ISSUE TITLE
cannot rebuild the project

### ISSUE THREAD

**Issue by heavenisaplaceonearth** [ue4plugins/StreetMap#33]
Hello I am doing some school project and have a trouble to use this module

I have made empty C++ project and put plugin files in project directory

and rebuild it

and I got Error

I got this log

c1 : ?R?}???h ???C?? error D8022 : 'E\blahblah(directory path)'
c1 : ?R?}???h ???C?? error D8022 : 'E\blhablahblah'
ERROR : UBT ERROR : Failed to produce ite, : 'E\blahblah'

and finally got pop up

worldimportprac could not be compiled. Try rebuilding from source manually

For integrity, I redownload the whole files and did it again and got same again.

is there any solutions to deal with it or I have to copy and paste all of the things by one by one?

**Comment by RaceTheMaSe** [comment]
See #34 . Its an easy fix.

**Comment by heavenisaplaceonearth** [comment]
Is that something to do with the C && C++ format?

By the way, my error is different from #34

My error log(above) doesn't display any class issues

Does my case is perfectly same for #34?
