### ISSUE TITLE
Cannot rebuild project

### ISSUE THREAD

**Issue by vinfamy** [ue4plugins/StreetMap#34]
Hi there, as instructed, I placed StreetMap into the Plugins folder and rebuild the project. Using UE 4.18.1

However, the rebuilding process returns the following errors:

C2228 --- left of '.GetSelectedObjects' must have class/struct/union --- LifePlay --- StreetMapComponentDetails.cpp --- Line 46

C2228 --- left of '.GetSelectedObjects' must have class/struct/union --- LifePlay --- StreetMapComponentDetails.cpp --- Line 61

Failed to produce item UE4Editor-StreetMapImporting.dll

The command "D:\Unreal418\UE_4.18\Engine\Build\BatchFiles\Rebuild.bat LifePlayEditor Win64 Development "D:\LifePlay\LifePlay.uproject" - waitmutex" exited with code -1. --- LifePlay --- Microsfot.MakeFile.Targets --- Line 49

**Comment by RaceTheMaSe** [comment]
Change the mentioned source file from <PluginDir>/Source/StreetMapImporting
to
"->GetSelectedObjects()" with an arrow, save it and it should compile fine. :)

**Comment by vinfamy** [comment]
Thanks. That did the trick. Issue closed :)
