### ISSUE TITLE
BuildingPoints (Look up coordinate for building name)

### ISSUE THREAD

**Issue by vinfamy** [ue4plugins/StreetMap#35]
Hi there,

First of all, great project! Everything seems to work great. Thank you.

Would you mind helping me understand what's in the Vector2d array BuildingPoints (Line 284, StreetMap.h) ? Most importantly, how can I convert a point on the rendered mesh, that the player's mouse cursor currently is on, into BuildingPoints as to lookup the StreetMap data asset and identify the building being clicked on?

The goal is to have the player hover his mouse over a building and its name would show up

Your help in pointing me in the right direction is much appreciated!

**Comment by vinfamy** [comment]
Update: Using the ConvertMouseLocationToWorldSpace node, I managed to obtain the world location and world direction vectors of the cursor. But then how would I go about converting these vectors into a format equivalent to the BuildingPoints to look up for building names?

**Comment by Hemofektik** [comment]
You could use World->LineTraceMultiByObjectType to find the collision point for your cursor.
The returned hit would have to be transformed into local space of the StreetMapActor. This local position's 2D part could be fed into FPolygonTools::IsPointInsidePolygon and tested against each building's FStreetMapBuilding::BuildingPoints to find the building that was actually hit.

**Comment by vinfamy** [comment]
Thank you for pointing me in the right direction. I managed to achieve what I was trying to do.

For those that are interested, the Get Hit Result Under Cursor By Channel node is quite useful for this. As stated in the comment, the IsPointInsidePolygon function doesn't work so well for edges, so if the player clicks on the sides of a building, it can be hit or miss whether it can identify the building or not. However, if the player clicks on the roof (especially right in the middle of it), it identifies the building perfectly, which is good enough for me.

Issue closed. Thank you for your help.
