### ISSUE TITLE
[Tutorial] For anyone tries to build on UE4.18

### ISSUE THREAD

**Issue by DeXtmL** [ue4plugins/StreetMap#37]
In StreetMapComponentDetails.cpp
Line 46: change ".GetSelectedObjects" to "->GetSelectedObjects"
Line 61: chagne ".GetSelectedActors" to "->GetSelectedActors"

That's all.
Build and enjoy

**Comment by derKosi** [comment]
If you have problems packaging ( UnrealBuildTool.exe result 5 ), try

natakaro (https://github.com/ue4plugins/StreetMap/issues/26)

> Remove "PropertyEditor" in StreetMapRuntime.Build.cs :)

**Comment by dodoleon** [comment]
I have change the StreetMapComponentDetials.cpp file.
But it still shows "The following modules are missing or built with a different engine version: UE4Editor-StreetMapRuntime.dll UE4Editor-StreetMapImporting.dll"

**Comment by JohnMath3w** [comment]
Same issue as @dodoleon. Cannot find .dll files.

**Comment by dodoleon** [comment]
@JohnMath3w  Close ue4 project adn then rebuild the c++ solution in vs. it will work.

**Comment by RogueSheep-nl** [comment]
Thanks @DeXtmL
