### ISSUE TITLE
Show street names in simulation

### ISSUE THREAD

**Issue by omgliliwtf** [ue4plugins/StreetMap#41]
Hi,

so i've been trying out this plugin and i was wondering if there was a way to also display the street names / names of sights from the osm data in the simulation.

i've been playing around a litte but i'm quite unexperienced with UE so i would really appreciate if someone could point me into the right direction with this!

**Comment by Hemofektik** [comment]
Hi, you could spawn a TextRenderActor where you want to display the names of nodes/ways. https://www.youtube.com/watch?v=t0LiVPLpPkg

**Comment by omgliliwtf** [comment]
Thank you so much for anwering, and for linking the video!
I think that will help me a lot!

**Comment by MikeFricker** [comment]
No plans for this right now.  TextRenderActor will do the job if you want it embedded into the 3D scene.  Otherwise there are multiple ways to draw 2D labels at the position of 3D objects in the scene, like the center of the road, by projecting world coords to viewport coords.
