### ISSUE TITLE
Can't add streetmap plugin to Unreal Engine

### ISSUE THREAD

**Issue by drift21** [ue4plugins/StreetMap#42]
Hi all,

I tried the past week to install this plugin on Unreal Engine Source Code using Visual Studio 2017. I had a lot of problems with it and it still doesn't work.

I installed the Unreal Enigne source code and copied this plugin into /engine/plugin/runtime/streetmap but the engine's solution couldn't be built correctly (without it the solution can be built without issues): when building with the plugin into engine's directory Visual Studio gives me two errors and three advertisments.

 I'm using:
Unreal Engine 4.19.2
Visual Studio 2017
I'd like to know which version of these software I need to let it work.
Regards.

**Comment by h656** [comment]
Hello,
This error is apparently due to a recent UnrealEngine feature called "Insert What You Use" (IWYU). A quick fix is to modify the build.cs files of the plugin. i.e
Add this line to your build.cs files in your plugin "bEnforceIWYU = false;" to get rid of these errors.
This can then compile on any version of the unreal engine.
Thanks.

**Comment by drift21** [comment]
Hi, 
thanks for answering. I'd like to know where I have to add ''bEnforceIWYU = false'' into StreetMapRuntime.build.cs and into StreetMapImporting.build.cs (which lines).
Thanks for the patience (I'm new at Visual Studio).
![streetmapimporting build cs image](https://user-images.githubusercontent.com/39413450/40588084-8bb0e528-61d8-11e8-8ecf-966e854aac48.png)
![streetmapruntime build](https://user-images.githubusercontent.com/39413450/40588085-8cbd355c-61d8-11e8-8f43-c4036a451823.png)

**Comment by h656** [comment]
StreetMapRuntime.Build.cs
"
// Copyright 2017 Mike Fricker. All Rights Reserved.

namespace UnrealBuildTool.Rules
{
	public class StreetMapRuntime : ModuleRules
	{
        public StreetMapRuntime(ReadOnlyTargetRules Target)
			: base(Target)
		{
            bEnforceIWYU = false;
            PrivateDependencyModuleNames.AddRange(
				new string[] {
                    "Core",
					"CoreUObject",
					"Engine",
					"RHI",
					"RenderCore",
					"ShaderCore"                    
                }
			);
		}
	}
}
"

StreetMapImporting.Build.cs

"
// Copyright 2017 Mike Fricker. All Rights Reserved.

namespace UnrealBuildTool.Rules
{
    public class StreetMapImporting : ModuleRules
    {
        public StreetMapImporting(ReadOnlyTargetRules Target)
			: base(Target)
        {
            bEnforceIWYU = false;
            PrivateDependencyModuleNames.AddRange(
                new string[] {
                    "Core",
                    "CoreUObject",
                    "Engine",
                    "UnrealEd",
                    "XmlParser",
                    "AssetTools",
                    "Projects",
                    "Slate",
                    "EditorStyle",
                    "SlateCore",
                    "PropertyEditor",
                    "RenderCore",
                    "ShaderCore",
                    "RHI",
                    "RawMesh",
                    "AssetTools",
                    "AssetRegistry",
                    "StreetMapRuntime"
                }
            );
        }
    }
}
"

Hope you get it :)!

**Comment by drift21** [comment]
Tkank you very much for the patience. I'll try it as soon as possibile.I hope I'll can ask you more questions if it doesn't work.

**Comment by dotcamdev** [comment]
Mhousse1247 fixed these errors in PR 4.19 & RenderProxy Update #45
