### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by magiros** [ue4plugins/StreetMap#43]
[build_error.txt](https://github.com/ue4plugins/StreetMap/files/2078928/build_error.txt)
I already change plugin source file.
StreetMapComponentDetails.cpp:
46 line ".GetSelectedObjects();"  => "->GetSelectedObjects();"
61 line ".GetSelectedActors();" => "->GetSelectedActors();"

and 
two cs file (StreetMapRuntime.Build.cs & StreetMapImporting.Build.cs)
add this line "bEnforceIWYU = false;"

but I can't build my project
and prompt print this error
StreetMapComponent.cpp(line 57) FStreetMapSceneProxy cannont instantiate abstract class

What should i do next?

Unreal engine version : 4.19.2
Visual Studio version : 2017 community 15.6.7

I am sorry for my lack of English ability. Thank you.
[build_error.txt](https://github.com/ue4plugins/StreetMap/files/2078929/build_error.txt)

**Comment by dotcamdev** [comment]
Mhousse1247 fixed these errors in PR 4.19 & RenderProxy Update #45
