### ISSUE TITLE
Create 3D Buildings not working/ Buildings generate flat.

### ISSUE THREAD

**Issue by Precognist** [ue4plugins/StreetMap#47]
I'm having an issue with the buildings being flat. Building level floor factor does nothing. All the other options for streets work, but the buildings do not extrude.

**Comment by Hemofektik** [comment]
Hi, the level floor factor only applies if the number of floors (BuildingLevels) is given for a building. Most buildings neither have the height nor the number of floors given, hence no extrusion.
