### ISSUE TITLE
No "StreetMapComponent"?

### ISSUE THREAD

**Issue by xplodwild** [ue4plugins/StreetMap#5]
Hey everyone,

I'm probably missing something big, but I can't seem to find the "Street Map Component" I need to put in my map to assign the Street Map Data to. I can import the .OSM file fine, and the plugin seems to have compiled fine (I copied StreetMap into a test project's Plugins folder, and once opening it prompted to rebuild the plugin, which built fine). Dragging the .OSM file worked fine, but then I can't find the Street Map Component to be able to assigned OSM file I dragged in.

Where is it? Did I miss something?

Thanks!

**Comment by MikeFricker** [comment]
Hey there!  Thanks for testing out the plugin.  You should be able to simply plop down an Empty Actor in your scene, then click "Add Component" in the Details tab to find the "Street Map" component in the drop down.  Is it really not showing up in there?

![streetmapcomponent](https://cloud.githubusercontent.com/assets/5840053/21595275/576e6f44-d0fa-11e6-9775-f82f51ea9b3d.png)

**Comment by xplodwild** [comment]
Oh, there it is! Ok, it is indeed still there - it wasn't obvious to me that it would be as a component. I was looking directly in the actors list rather than in the components. I guess I havent recovered from new year's eve properly yet :)

Anyway, thanks for the hint, I'll pop a PR tomorrow to update the docs to make  that clearer. And thanks for this awesome plugin, I was thinking about creating one myself :) I'll look forward to contribute to it as soon as I have some time to play a bit more with it and start building my next project.

Cheers!
