### ISSUE TITLE
Compiling errors for 4.18

### ISSUE THREAD

**Issue by oppne** [ue4plugins/StreetMap#51]
Got alot of errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3646	'VertexBuffer': unknown override specifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	104	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	104	
Error	C3646	'IndexBuffer32': unknown override specifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	107	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	107	
Error	C3668	'FStreetMapSceneProxy::GetTypeHash': method with override specifier 'override' did not override any base class methods	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	77	
Error	C3646	'VertexBuffer': unknown override specifier	Streetmapper	n:\ue4streetmap\ue4\streetmapper\plugins\streetmap\source\streetmapruntime\StreetMapSceneProxy.h	104	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	n:\ue4streetmap\ue4\streetmapper\plugins\streetmap\source\streetmapruntime\StreetMapSceneProxy.h	104	
Error	C3646	'IndexBuffer32': unknown override specifier	Streetmapper	n:\ue4streetmap\ue4\streetmapper\plugins\streetmap\source\streetmapruntime\StreetMapSceneProxy.h	107	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	n:\ue4streetmap\ue4\streetmapper\plugins\streetmap\source\streetmapruntime\StreetMapSceneProxy.h	107	
Error	C3668	'FStreetMapSceneProxy::GetTypeHash': method with override specifier 'override' did not override any base class methods	Streetmapper	n:\ue4streetmap\ue4\streetmapper\plugins\streetmap\source\streetmapruntime\StreetMapSceneProxy.h	77	
Error	C2661	'FLocalVertexFactory::FLocalVertexFactory': no overloaded function takes 2 arguments	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	13	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	21	
Error	C2228	left of '.Indices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	21	
Error	C2440	'=': cannot convert from 'const FVector2D' to 'float'	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	38	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	43	
Error	C2228	left of '.InitFromDynamicVertex' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	43	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	65	
Error	C2228	left of '.PositionVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	65	
Error	C2228	left of '.ReleaseResource' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	65	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	66	
Error	C2228	left of '.StaticMeshVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	66	
Error	C2228	left of '.ReleaseResource' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	66	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	67	
Error	C2228	left of '.ColorVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	67	
Error	C2228	left of '.ReleaseResource' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	67	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	68	
Error	C2228	left of '.ReleaseResource' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	68	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	82	
Error	C2228	left of '.PositionVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	82	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	83	
Error	C2228	left of '.StaticMeshVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	83	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	84	
Error	C2228	left of '.ColorVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	84	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	85	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	144	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	151	
Error	C2228	left of '.Indices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	151	
Error	C2228	left of '.Num' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	151	
Error	C2789	'IndexCount': an object of const-qualified type must be initialized	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	151	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	
Error	C2228	left of '.PositionVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	
Error	C2228	left of '.GetNumVertices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	163	
Error	C2228	left of '.Indices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	163	
Error	C2228	left of '.Num' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	163	
Error	C2789	'IndexCount': an object of const-qualified type must be initialized	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	163	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	164	
Error	C2228	left of '.PositionVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	164	
Error	C2228	left of '.GetNumVertices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	164	
Error	C2065	'IndexBuffer32': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	177	
Error	C2228	left of '.Indices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	177	
Error	C2228	left of '.Num' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	177	
Error	C2789	'IndexCount': an object of const-qualified type must be initialized	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	177	
Error	C2065	'VertexBuffer': undeclared identifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	178	
Error	C2228	left of '.PositionVertexBuffer' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	178	
Error	C2228	left of '.GetNumVertices' must have class/struct/union	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	178	
Error	C3646	'VertexBuffer': unknown override specifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	104	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	104	
Error	C3646	'IndexBuffer32': unknown override specifier	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	107	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	107	
Error	C3668	'FStreetMapSceneProxy::GetTypeHash': method with override specifier 'override' did not override any base class methods	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.h	77	
Error		Failed to produce item: N:\UE4Streetmap\UE4\Streetmapper\Plugins\StreetMap\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-StreetMapRuntime.lib	Streetmapper	N:\UE4Streetmap\UE4\Streetmapper\Intermediate\ProjectFiles\ERROR	1	
Error	MSB3073	The command "F:\UT\UE_4.18\Engine\Build\BatchFiles\Rebuild.bat StreetmapperEditor Win64 Development "N:\UE4Streetmap\UE4\Streetmapper\Streetmapper.uproject" -waitmutex" exited with code -1.	Streetmapper	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets	49

**Comment by p-schulz** [comment]
Did you already try checking out to commit cbd35e47 as the current state works only for 4.19?
