### ISSUE TITLE
Compiling error UE4.20

### ISSUE THREAD

**Issue by Shazter** [ue4plugins/StreetMap#54]
I followed the guide to build and VS2017 throws this build error

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static void __cdecl UNavigationSystem::UpdateComponentInNavOctree(class UActorComponent &)" (__imp_?UpdateComponentInNavOctree@UNavigationSystem@@SAXAEAVUActorComponent@@@Z) referenced in function "protected: void __cdecl UStreetMapComponent::ClearCollision(void)" (?ClearCollision@UStreetMapComponent@@IEAAXXZ)	OSMTest2

**Comment by RaceTheMaSe** [comment]
I did two things:
1. Add "NavigationSystem" to build.cs
2. Change StreetMapComponent.cpp:
`void UStreetMapComponent::UpdateNavigationIfNeeded()
{
	if (bCanEverAffectNavigation || bNavigationRelevant)
	{
		//UNavigationSystem::UpdateComponentInNavOctree(*this);
		FNavigationSystem::UpdateComponentData(*this);
	}
}`

**Comment by Shazter** [comment]
Could you add a pullrequest with the changes, then rep. owner can merge after approval
