### ISSUE TITLE
Can't compile the plugin - UE 4.19.2 - Windows 10

### ISSUE THREAD

**Issue by Killy85** [ue4plugins/StreetMap#58]
Hello there,

I'm having an issue while adding the plugins to the project.

UE4 editor just tell me he can't compile this plugin due to a missing binary.

Error messages:

> Binaries for the 'StreetMap' plugin are missing or incompatible with the current engine version.

>Plugin 'StreetMap' failed to load because module 'StreetMapRuntime' could not be found. Please ensure the plugin is properly installed , otherwise consider disabling the plugin for this project.

I'm quite sure the installation is correct (download and unzip of the git repo).

Did someone else had the same trouble using the plugin and found a solution?

By the way, i'm using UE4.19.2 on windows 10.

Thanks in advance,

**Comment by HolyBugger** [comment]
Do you fix it ? I have the problem too. I'm using UE4.2.0 on Windows 10.

**Comment by Killy85** [comment]
Hey HolyBugger,


I have read the differents issues of the repo and there is one about to make it compatible with blueprints projects. Which mean it's not.

So I start a new c++ project and it's working like a charm!!

Hope that's help you.
