### ISSUE TITLE
Compiling error for UE4.19

### ISSUE THREAD

**Issue by tanglrHello** [ue4plugins/StreetMap#59]
After the command "make launch", UE shows an error window : "The following modules are missing or built with a different engine version: libUE4Editor-StreetMapRuntime.so  libUE4Editor-StreetMapImporting.so Would you like to rebuild them now?"
After I clicked "Yes", another error window shows "CarlaUE4 could not be compiled. Try rebuilding from source manually."

I have followed the instruction in issue 37, but found the StreetMapComponentDetails.cpp has already been corrected as described.
I also tried "Remove "PropertyEditor" in StreetMapRuntime.Build.cs", but still not work.

What can I do to fix it? I'm running it on Ubuntu16.04

**Comment by Heppetisprett** [comment]
I have the same issue with 4.19 win10.64 , 4.19 does not want to compile at all, 4.21 gives me "could not be compiled. Try rebuilding from source manually."

**Comment by c00t** [comment]
>           I have the same issue with 4.19 win10.64 , 4.19 does not want to compile at all, 4.21 gives me "could not be compiled. Try rebuilding from source manually."

I switch to the pull request #52 branch, then it works for 4.20.3. this method may be useful to  4.21 as well.

**Comment by c00t** [comment]
>           I have the same issue with 4.19 win10.64 , 4.19 does not want to compile at all, 4.21 gives me "could not be compiled. Try rebuilding from source manually."

hey! Heppetisprett, I make it works for 4.21, with #52 branch, you should also add
 `            PCHUsage = ModuleRules.PCHUsageMode.NoSharedPCHs;
            PrivatePCHHeaderFile = "StreetMapRuntime.h";` to the file StreetMapRuntime.Build.cs, and 
`            PCHUsage = ModuleRules.PCHUsageMode.NoSharedPCHs;
            PrivatePCHHeaderFile = "StreetMapImporting.h";` to the file StreetMapImporting.Build.cs.

Example:

``` C#
// Copyright 2017 Mike Fricker. All Rights Reserved.

namespace UnrealBuildTool.Rules
{
	public class StreetMapRuntime : ModuleRules
	{
        public StreetMapRuntime(ReadOnlyTargetRules Target): base(Target)
		{
				PCHUsage = ModuleRules.PCHUsageMode.NoSharedPCHs;
				PrivatePCHHeaderFile = "StreetMapRuntime.h";
				//PrivatePCHHeaderFile = "StreetMapImporting.h";
				PrivateDependencyModuleNames.AddRange(
				new string[] {
					"Core",
					"CoreUObject",
					"Engine",
					"RHI",
					"RenderCore",
					"ShaderCore",
					"PropertyEditor"
				}
			);
		}
	}
}
```

**Comment by Heppetisprett** [comment]
c00t , Youre a genious ! I can confirm that 4.21 compiles with your fix (and #52 + #46)

**Comment by sandwich189** [comment]
Hi, I followed your fix but i still receive the same Error. I'm on Ubuntu 18.04

**Comment by coliverra** [comment]
View this topic:  https://vk.com/topic-152179829_40088077

Can run with Unreal 4.22. More I needed to remove "PropertyEditor", of the file StreetMapRuntime.Build.cs and StreetMapImporting
