### ISSUE TITLE
Document OSM editing

### ISSUE THREAD

**Issue by Matthias84** [ue4plugins/StreetMap#6]
Hi there,

looks like an pretty interesting project. As most users will not be familar with OSM and the community, I would recommend to add a small section to readme.md that describes how to edit OSM and which edits are welcome.

P.S: If you need help, I will add an PR

**Comment by HeadClot** [comment]
This would be most welcome :)

**Comment by Matthias84** [comment]
I started an PR, hope I found the right words ;) 

FYI: Someone started an [OSM wiki page](https://wiki.openstreetmap.org/wiki/Unreal_Engine) on this project. So if you want to scale it, this might be an good point to work with OSM community :)
