### ISSUE TITLE
Trying to compile with UE4 4.23 on Windows 10 and VS2019

### ISSUE THREAD

**Issue by basketballspurs** [ue4plugins/StreetMap#70]
I've spent most of the day trying all the different version I can find but keep getting the same error when I try to rebuild. Have done the generate project files and rebuild but still nothing.

I tried the master branch and also the https://github.com/keru1264/StreetMap fork which fixed the ShaderCore error, but still can't get it to work.

The messages I get are

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0304	no instance of overloaded function "FDynamicPrimitiveUniformBuffer::Set" matches the argument list	StreetMapTesting	C:\Users\tomwo\Documents\Unreal Projects\StreetMapTesting\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0020	identifier "UseEditorDepthTest" is undefined	StreetMapTesting	C:\Users\tomwo\Documents\Unreal Projects\StreetMapTesting\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'UseEditorDepthTest': identifier not found	StreetMapTesting	C:\Users\tomwo\Documents\Unreal Projects\StreetMapTesting\Plugins\StreetMap\Source\StreetMapRuntime\StreetMapSceneProxy.cpp	154	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4996	'UStaticMesh::SourceModels': Please do not access this member directly; use UStaticMesh::GetSourceModel(LOD) or UStaticMesh::GetSourceModels(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	StreetMapTesting	C:\Users\tomwo\Documents\Unreal Projects\StreetMapTesting\Plugins\StreetMap\Source\StreetMapImporting\StreetMapComponentDetails.cpp	291	

Any ideas?

**Comment by kamex-kumax** [comment]
I seem that I could fix that, in my forked project.
It doesn't work perfectly, but I solved compile error in my environment.
[kamex-kumax/StreetMap](https://github.com/kamex-kumax/StreetMap)

I pushed 4 commits, but the main commit is the only last one.
[72b821f9c0ca16d184b7cb6554a88af0658caab4](https://github.com/kamex-kumax/StreetMap/commit/)
I updated  line 154 in Source/StreetMapRuntime/StreetMapSceneProxy.cpp 
`DynamicPrimitiveUniformBuffer.Set(GetLocalToWorld(), GetLocalToWorld(), GetBounds(), GetLocalBounds(), true, false, UseEditorDepthTest());`
to
`DynamicPrimitiveUniformBuffer.Set(GetLocalToWorld(), GetLocalToWorld(), GetBounds(), GetLocalBounds(), true, false, DrawsVelocity(), false);`

**Comment by basketballspurs** [comment]
That worked perfectly, thanks.

**Comment by Heite92** [comment]
> I seem that I could fix that, in my forked project.
> It doesn't work perfectly, but I solved compile error in my environment.
> [kamex-kumax/StreetMap](https://github.com/kamex-kumax/StreetMap)

Did you remove the ground because it didn't work?

**Comment by kamex-kumax** [comment]
I just updated 1 function.
I DID NOT remove any processes also drawing ground.
