### ISSUE TITLE
4.23 Plugin failed to load because runtime "StreetMapRuntime" could not be found

### ISSUE THREAD

**Issue by dagillespie** [ue4plugins/StreetMap#71]
Hi
I'm trying to test out your plugin however I can't get it to open in Unreal 4.23.0. I get the following error:

Plugin failed to load because runtime "StreetMapRuntime" could not be found, Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.

I get this when opening the editor irrespective of any project being loaded C++ or otherwise.

**Comment by XNRavenZen** [comment]
I get an error "Could not find definition for module 'ShaderCore', (referenced via Target -> StreetMapRuntime.Build.cs)". It seems to be removed from UE 4.21 onwards.
