### ISSUE TITLE
Using 4.23.1 and failed to compile.

### ISSUE THREAD

**Issue by yoon1012** [ue4plugins/StreetMap#72]
I copied whole folder into Plugins in my Unreal project and tried to compile but got an error message.

ERROR: Could not find definition for module 'ShaderCore', (referenced via Target -> StreetMapRuntime.Build.cs)

**Comment by kakhlaghi** [comment]
Bumping because I have the same error.

**Comment by joelelrocker** [comment]
Giving this another nudge as I too am having the same issue.

**Comment by levi217** [comment]
Anyone figure this out? Running into same prob, even when running on 4.22

**Comment by brybalicious** [comment]
Same problem on 4.26

**Comment by brybalicious** [comment]
But, best to use the release from GameInstitute which is updated for 4.26. Got that working in the end
