### ISSUE TITLE
4.24 Compilation fails

### ISSUE THREAD

**Issue by vxvzhaolei** [ue4plugins/StreetMap#75]
Could not find definition for module 'ShaderCore',(referenced via Target - > StreetMaplmporting.Build.cs)

**Comment by kprimo** [comment]
same problem, have you ever solved it?

**Comment by GamesUKStudios** [comment]
we have the same issue can anyone answer us it's urgent

**Comment by udithaunreal** [comment]
Shadercore is no longer needed as it was merged with Rendercore

**Comment by GamesUKStudios** [comment]
how can i get it to work for ue4.24

**Comment by udithaunreal** [comment]
I am also trying to get it to work for 4.24 no luck so far.

**Comment by udithaunreal** [comment]
@GamesUKStudios  you can try by taking off the ShaderCore from the buil.cs files and then try to build. I tried but although that issue was not seen again, some other reference errors popped up. 

Let me know how it goes.

**Comment by mbpictures** [comment]
I'm interested in this as well! I got all the reference & compile errors fixed by some google & API work but the Engine crashes after placing the OSM asset in the viewport...

**Comment by GamesUKStudios** [comment]
@udithaunreal no luck can you help please need it urgently for my game info@gamesukstudios.co.uk

**Comment by GamesUKStudios** [comment]
if anyone can send me a working version please contact me it is urgent to get this done @

**Comment by mbpictures** [comment]
If anyone fixes this issue, maybe he can create a PR or a fork of the repo, so we can access it all? :) I can try to redo my fixes, but as I said. It crashed.

**Comment by mbpictures** [comment]
Good news! @GamesUKStudios @udithaunreal ! I got it working, the only issue is, that not all buildings are 3D :/ Here an screenshot:
![image](https://user-images.githubusercontent.com/2772553/81725772-a3089a80-9486-11ea-9a14-1a0e49583647.png)
I fixed it for 4.24. I will create an PR in a few hours.

**Comment by mbpictures** [comment]
update: PR created, see #77

**Comment by GamesUKStudios** [comment]
great job @mbpictures thank you i just need the roads anyway can you send me the plugin my email ceo@gamesukstudios.co.uk

**Comment by mbpictures** [comment]
Just clone this repo and checkout Pull-Request #77 . Or clone my fork directly [here](https://github.com/mbpictures/StreetMap)

**Comment by vxvzhaolei** [comment]
Hello, there is no way to solve the 4.24 compile failure problem. I can give you a link that might help you
https://github.com/kamex-kumax/StreetMap
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GamesUKStudios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 凌晨5:34
收件人:&nbsp;"ue4plugins/StreetMap"<StreetMap@noreply.github.com&gt;;
抄送:&nbsp;"灬夏丨末丶"<vxvzhaolei@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ue4plugins/StreetMap] 4.24 Compilation fails (#75)





 
great job @mbpictures thank you i just need the roads anyway can you send me the plugin my email ceo@gamesukstudios.co.uk

**Comment by udithaunreal** [comment]
> Good news! @GamesUKStudios @udithaunreal ! I got it working, the only issue is, that not all buildings are 3D :/ Here an screenshot:
> ![image](https://user-images.githubusercontent.com/2772553/81725772-a3089a80-9486-11ea-9a14-1a0e49583647.png)
> I fixed it for 4.24. I will create an PR in a few hours.

WOW thanks mate good job
