### ISSUE TITLE
Can't import plugin to project

### ISSUE THREAD

**Issue by kisgergo99** [ue4plugins/StreetMap#83]
I have some problems with importing the plugin to the project. When I unzip it to the plugins folder, and try to open my project it's got the error that can't be rebuild. I have UE 4.26.1.

**Comment by wildfat** [comment]
@kisgergo99 Have the same problem. Have you some succeed with it?

**Comment by wildfat** [comment]
Check this https://github.com/ue4plugins/StreetMap/issues/84#issue-866834054
