### ISSUE TITLE
UE 4.27.0 compile error

### ISSUE THREAD

**Issue by AidinKornejady** [ue4plugins/StreetMap#88]
Hi guys
I'm trying to add the StreetMap plugin (got the code and put it in a separate folder in my project folder), but I got this error that says" MyProject could not be compiled. Try rebuilding from source manually". I guess it's not compatible with 4.27 yet. Any help? Thanks in advance.

**Comment by WilledgeR** [comment]
What is your error daee?

**Comment by rkpatrick** [comment]
Not sure if it's going to be the same issue, but I'm trying to build it Unreal 5.0, and I get a cascade of errors/warnings that start with:
_StreetMap\Source\StreetMapRuntime\Private\StreetMapComponent.cpp(104): error C2679: binary '=': no operator found which takes a right-hand operand of type 'FVector' (or there is no acceptable conversion)_
