### ISSUE TITLE
Unrecognized type 'FVector3f' - type must be a UCLASS, USTRUCT or UENUM

### ISSUE THREAD

**Issue by rgomesdn** [ue4plugins/StreetMap#93]
I already tried compiling on versions 5.0, 4.27 and 4.26. But I always get this error

Build started...
1>------ Skipped Build: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: osmfil, Configuration: Development_Editor x64 ------
2>Creating makefile for osmfilEditor (no existing makefile)
2>Parsing headers for osmfilEditor
2>  Running UnrealHeaderTool "D:\UNREAL_PROJECTS\MyGames\UE_4,26\osmfil\osmfil.uproject" "D:\UNREAL_PROJECTS\MyGames\UE_4,26\osmfil\Intermediate\Build\Win64\osmfilEditor\Development\osmfilEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\rdn10\AppData\Local\UnrealBuildTool\Log_UHT.txt" -installed
2>D:/UNREAL_PROJECTS/MyGames/UE_4,26/osmfil/Plugins/StreetMap/Source/StreetMapRuntime/StreetMapSceneProxy.h(16): error : Unrecognized type 'FVector3f' - type must be a UCLASS, USTRUCT or UENUM
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "C:\Unreal_Engine\UE_4.26\Engine\Build\BatchFiles\Build.bat osmfilEditor Win64 Development -Project="D:\UNREAL_PROJECTS\MyGames\UE_4,26\osmfil\osmfil.uproject" -WaitMutex -FromMsBuild" exited with code 6.
2>Done building project "osmfil.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

**Comment by AbdelrhmanHassan1** [comment]
I am facing the same problem, did you figured how to solve it?

**Comment by MikeFricker** [comment]
Wasn't able to reproduce the UnrealHeaderTool issue above.

**Comment by aidenyao** [comment]
I am facing the same problem

**Comment by JarvisLee0423** [comment]
Did anyone solve this problem? I met the same problem when processing make command in UE4.
