### ISSUE TITLE
when Font ReImport,will make crash

### ISSUE THREAD

**Issue by NameLJK** [ue4plugins/StreetMap#94]
bool UStreetMapReimportFactory::CanReimport( UObject* Obj, TArray<FString>& OutFilenames )
{
	UStreetMap* StreetMap = Cast<UStreetMap>( Obj );
	if( StreetMap != nullptr )
	{
		OutFilenames.Add( StreetMap->AssetImportData->GetFirstFilename() );
	}
	return true;
} /*reason*/

/*fix*/
bool UStreetMapReimportFactory::CanReimport( UObject* Obj, TArray<FString>& OutFilenames )
{
	UStreetMap* StreetMap = Cast<UStreetMap>( Obj );
	if( StreetMap != nullptr )
	{
		OutFilenames.Add( StreetMap->AssetImportData->GetFirstFilename() );
		return true;
	}
	return false;
}

**Comment by MikeFricker** [comment]
Thanks for the fix, commited.
