### ISSUE TITLE
UE 5.1.1 Map data doesn't appear in viewport just anchor point.

### ISSUE THREAD

**Issue by joematrix77** [ue4plugins/StreetMap#95]
I get it to compile on UE5.1.1 but when I Import an OSM file I get no output in the view port just the anchor. I figured I'll downgrade and migrate but that didn't work.

**Comment by MikeFricker** [comment]
Yeah, I can reproduce this as well in 5.2.  The map is there but only renders if its selected.  You can select it in the World Outliner.  If you use the "Generate Mesh" button in the details panel, you can at least make a static mesh representation of the map.  I'll investigate further when I have a chance!

**Comment by joematrix77** [comment]
I also got the same results but when I generate the mesh it creates it like if its wrapped in a bound node in Houdini to large for the world map even with streaming enabled.

**Comment by MikeFricker** [comment]
Latest commit should fix it!  Thanks for letting me know.

For the generated mesh being too big, I guess that would depend on the metrics of your OSM data.  But in any case, the built-in rendering for the map and also the mesh generator are really just simplistic examples.  For a real city with streaming good visuals, you'd probably want to interpret the loaded OSM map data offline to generate nice looking worlds.

**Comment by joematrix77** [comment]
Thanks, I'll compile it now.

**Comment by omarabdellatif99** [comment]
> I get it to compile on UE5.1.1 but when I Import an OSM file I get no output in the view port just the anchor. I figured I'll downgrade and migrate but that didn't work.

How did you get it compile as i get a message where that its not compatible with the version am using actually am using 5.3 should i try with your version 5.1 ?
